### ISSUE TITLE
Update the sc2 library with burny's python-sc2 library. (Fixes buff ids)

### ISSUE THREAD

**Issue by DomShark** [ProBotsAI/python-sc2-bot-template#10]
I created a pull request that adds this change. I made sure to test it with the starter bot, and it runs with no issues.

**Comment by brean** [comment]
Why did you copy it over? why not either
- use a git submodule or
- use a pip requirement on burnysc2 (run `pip3 install burnysc2`)

as the sc2-folders from 
https://github.com/ProBotsAI/probots-sc2-bot-template/tree/master/sc2
and 
https://github.com/BurnySc2/python-sc2/tree/develop/sc2
are identical.

I think think just referencing it in some way should be easier for maintenance.
